version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    expose:
      - 5432
  app:
    build: .
    command: uvicorn main:app --host=0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
